name: srm_final
description: Final SRM with multuple method. Produc by TNB/bachtiyar93
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  progress_indicators: ^0.1.5
  provider: ^4.3.2+2
  webview_flutter: ^1.0.7
  intl: ^0.16.1
  image_picker: ^0.6.7+14
  mime: ^0.9.7
  toast: ^0.1.5
  flushbar: ^1.10.4
  firebase_messaging: ^7.0.3
  shimmer: ^1.1.2
  google_fonts: ^1.1.1
  shared_preferences: ^0.5.12+4
  custom_progress_dialog: ^1.0.5
  percent_indicator: ^2.1.8
  http: ^0.12.2
  crypto: ^2.1.5
  validators: ^2.0.1
  firebase_analytics: any
  firebase_core: ^0.5.2+1
  #Network cached
  cached_network_image: ^2.4.1
  #design dari adobe di
  adobe_xd: ^1.0.0+1
  # Hive
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  # state management
  stacked: ^1.7.6
  carousel_pro: ^1.0.0
  # third party usable services
  stacked_services: ^0.6.0+1
  get_it:
  injectable:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  #generators
  hive_generator: ^0.8.2
  build_runner:
  auto_route_generator:
  injectable_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/ic_bed.png
    - assets/ic_call.png
    - assets/ic_curtains.png
    - assets/ic_logo.png
    - assets/ic_map.png
    - assets/ic_money.png
    - assets/ic_reward.png
    - assets/ic_rod.png
    - assets/ic_roll.png
    - assets/ic_send.png
    - assets/ic_transact.png
    - assets/ic_world.png
    - assets/qa.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
