/// Generated by AssetsRefGenerator on 2020/10/26
class Res {
  static const String ic_send = "assets/ic_send.png";
  static const String ic_curtains = "assets/ic_curtains.png";
  static const String ic_bed = "assets/ic_bed.png";
  static const String ic_map = "assets/ic_map.png";
  static const String qa = "assets/qa.png";
  static const String ic_transact = "assets/ic_transact.png";
  static const String ic_logo = "assets/ic_logo.png";
  static const String ic_call = "assets/ic_call.png";
  static const String ic_world = "assets/ic_world.png";
  static const String ic_reward = "assets/ic_reward.png";
  static const String ic_money = "assets/ic_money.png";
}
